/**
 * Canonical URS field allowlist for current_state.fields projection.
 * Source: docs/specs/state-engine.md § Canonical fields and
 *         docs/specs/state-delta-detection.md § Companion fields.
 */
export const URS_ALLOWED_BASE_KEYS = [
  // Core URS scalars (state-engine.md canonical fields)
  'masteryScore',
  'stabilityScore',
  'timeSinceReinforcement',
  'riskSignal',
  // skill is allowed because it identifies the dominant skill (string, not nested)
  'skill',
] as const;

export type URSAllowedBaseKey = (typeof URS_ALLOWED_BASE_KEYS)[number];

export const URS_ALLOWED_NUMERIC_BASE_KEYS = [
  'masteryScore',
  'stabilityScore',
  'timeSinceReinforcement',
  'riskSignal',
] as const;

export type URSAllowedNumericBaseKey = (typeof URS_ALLOWED_NUMERIC_BASE_KEYS)[number];

/**
 * Companion-field suffixes generated by state-delta-detection.md.
 * A field name is allowed iff it equals one of URS_ALLOWED_BASE_KEYS or
 * starts with one of the numeric base keys followed by one of these suffixes.
 */
export const URS_COMPANION_SUFFIXES = [
  '_delta',
  '_direction',
  '_delta_delta',
  '_delta_direction',
  '_delta_delta_delta',
  '_delta_delta_direction',
  // higher-order deltas are intentionally omitted — they are diagnostic noise,
  // not URS-grade. Bound the surface at 3rd-order deltas.
] as const;

export type URSCompanionSuffix = (typeof URS_COMPANION_SUFFIXES)[number];

export type URSAllowedKey =
  | URSAllowedBaseKey
  | `${URSAllowedNumericBaseKey}${URSCompanionSuffix}`;

export function isAllowedURSKey(key: string): boolean {
  if ((URS_ALLOWED_BASE_KEYS as readonly string[]).includes(key)) return true;
  for (const base of URS_ALLOWED_NUMERIC_BASE_KEYS) {
    for (const suffix of URS_COMPANION_SUFFIXES) {
      if (key === `${base}${suffix}`) return true;
    }
  }
  return false;
}
